# Configuration
DICTIONARIES = codetypo/data/dictionary*.txt codetypo/tests/data/*.wordlist
GENERATED := codetypo/data/dictionary_en_to_en-OX_AUTOGENERATED.txt
VENV = .venv
PYTHON = $(VENV)/bin/python3
PIP = $(VENV)/bin/pip
COVERAGE = $(VENV)/bin/coverage
BANDIT = $(VENV)/bin/bandit
SAFETY = $(VENV)/bin/safety
PYTEST = $(VENV)/bin/pytest

# Default minimum test coverage percentage
COVERAGE_MIN = 90

# Python interpreter to use for virtualenv
PYTHON_VERSION = python3.12

# Phony targets
.PHONY: all check check-dictionaries sort-dictionaries trim-dictionaries \
        check-dist test pytest ruff mypy format clean help dev venv build install \
        security-check dependency-check coverage-report check-coverage \
        check-dependencies update-dependencies

# Help target to display all targets with descriptions
help: ## Display this help message
	@echo '\nAvailable targets:'
	@echo '  all                  - Build everything (generated files, check dictionaries, man page)'
	@echo '  check               - Run all checks (dictionaries, dist, tests, linting)'
	@echo '  test                - Run all tests (pytest and mypy)'
	@echo '  pytest              - Run pytest suite with coverage'
	@echo '  mypy                - Run static type checking'
	@echo '  ruff                - Run ruff linter'
	@echo '  format              - Format code and sort imports'
	@echo '  build               - Build distribution packages'
	@echo '  install             - Install the package in development mode'
	@echo '  check-dist          - Check if package can be built and distributed'
	@echo '  dev                 - Set up development environment (create venv and install deps)'
	@echo '  venv                - Create a Python virtual environment'
	@echo '  clean               - Remove generated files and virtual environment'
	@echo '  security-check      - Run security checks (bandit and safety)'
	@echo '  dependency-check    - Check for outdated dependencies'
	@echo '  check-dependencies  - Check if all dependencies are installed'
	@echo '  update-dependencies - Update all dependencies to their latest versions'
	@echo '  coverage-report     - Generate and display coverage report'
	@echo '  check-coverage      - Check if test coverage meets minimum requirements'
	@echo '  help                - Display this help message'

# Build targets
all: $(GENERATED) check-dictionaries codetypo.1 build

# Build distribution packages
build:
	@echo "Building distribution packages..."
	$(PYTHON) -m build

# Install the package in development mode
install:
	@echo "Installing package in development mode..."
	$(PIP) install -e .

check: $(GENERATED) check-dictionaries check-dist test ruff

test: pytest mypy check-coverage

# Dictionary management
check-dictionaries: sort-dictionaries
	@echo "Checking dictionaries for formatting issues..."
	@for dictionary in ${DICTIONARIES}; do \
		if grep -E -n "^\s*$$|\s$$|^\s" "$$dictionary"; then \
			echo "[ERROR] Dictionary $$dictionary contains formatting issues."; \
			echo "Run 'make trim-dictionaries' to fix."; \
			exit 1; \
		fi; \
	done
	@if command -v pytest > /dev/null; then \
		echo "Running dictionary tests..."; \
		pytest codetypo/tests/test_dictionary.py -v; \
	else \
		echo "[ERROR] Test dependencies not installed."; \
		echo "Install with: pip install -e \".[dev]\""; \
		exit 1; \
	fi

sort-dictionaries: $(GENERATED)
	@echo "Sorting dictionary files..."
	pre-commit run --all-files file-contents-sorter

$(GENERATED): codetypo/data/dictionary_en-GB_to_en-US.txt ./tools/normalize_spelling.sh
	@echo "Generating $@..."
	./tools/normalize_spelling.sh $< > $@

trim-dictionaries: $(GENERATED)
	@echo "Trimming whitespace in dictionaries..."
	@for dictionary in ${DICTIONARIES}; do \
		echo "Processing $$dictionary"; \
		sed -E -i.bak -e 's/^[[:space:]]+//; s/[[:space:]]+$$//; /^$$/d' "$$dictionary" && rm -f "$$dictionary.bak"; \
	done

# Documentation
codetypo.1: codetypo.1.include Makefile
	@echo "Generating man page..."
	PYTHONPATH=. help2man codetypo --include codetypo.1.include --no-info --output $@
	sed -i '' '/\.SS "Usage/,+2d' $@

# Testing & Linting
pytest: sort-dictionaries
	@if command -v $(PYTEST) > /dev/null; then \
		echo "Running tests with coverage..."; \
		$(PYTEST) codetypo -v --cov=codetypo --cov-report=term-missing --cov-fail-under=$(COVERAGE_MIN); \
	else \
		echo "[ERROR] Test dependencies not installed."; \
		echo "Install with: pip install -e \".[dev]\""; \
		exit 1; \
	fi

mypy:
	@echo "Running static type checking..."
	mypy .

ruff:
	@echo "Running ruff linter..."
	pre-commit run --all-files ruff

format:
	@echo "Formatting code..."
	black .
	isort .

# Distribution
check-dist: check-dependencies
	@echo "Checking distribution..."
	$(eval TMP := $(shell mktemp -d))
	$(PYTHON) -m build -o $(TMP)
	twine check --strict $(TMP)/*
	@rm -rf $(TMP)
	@echo "Distribution check passed!"

# Development environment
venv:
	@echo "Creating Python virtual environment..."
	python3 -m venv $(VENV)
	$(PIP) install --upgrade pip setuptools wheel

# Install development dependencies
dev: venv
	@echo "Installing development dependencies..."
	$(PIP) install -e ".[dev]"
	@echo "\nDevelopment environment setup complete!"
	@echo "To activate the virtual environment, run:"
	@echo "  source $(VENV)/bin/activate"

# Security and Dependencies
security-check: venv
	@echo "Running security checks..."
	@if ! command -v $(BANDIT) > /dev/null; then \
		$(PIP) install bandit safety; \
	fi
	@echo "\n=== Running Bandit security scanner ==="
	$(BANDIT) -r codetypo -lll --skip B101
	@echo "\n=== Checking for vulnerable dependencies ==="
	$(PIP) install safety
	safety check --full-report

# Dependency management
check-dependencies:
	@echo "Checking if all dependencies are installed..."
	@$(PIP) check \
		&& echo "All dependencies are installed." \
		|| { echo "Some dependencies are missing or have conflicts. Run 'make dev' to install/update them."; exit 1; }

dependency-check:
	@echo "Checking for outdated dependencies..."
	$(PIP) list --outdated

update-dependencies:
	@echo "Updating all dependencies..."
	$(PIP) install --upgrade pip setuptools wheel
	$(PIP) install -U -e ".[dev]"
	$(PIP) install -e .

# Test coverage
coverage-report:
	@echo "Generating coverage report..."
	$(COVERAGE) report -m --skip-covered

check-coverage: coverage-report
	@echo "Checking test coverage..."
	@$(COVERAGE) report --fail-under=$(COVERAGE_MIN) > /dev/null 2>&1 || \
		{ echo "\n[ERROR] Test coverage is below $(COVERAGE_MIN)%. Cannot proceed."; \
		$(COVERAGE) report; exit 1; }

# Cleanup
clean:
	@echo "Cleaning up..."
	rm -f codetypo.1
	rm -rf .coverage .coverage.* htmlcov .pytest_cache .mypy_cache .ruff_cache
	@echo "Removing virtual environment..."
	rm -rf $(VENV) build/ dist/ *.egg-info/
